/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AddressId = bigint;
export interface CartItem {
  'unitPriceCents' : bigint,
  'menuItemName' : string,
  'customizations' : Array<SelectedCustomization>,
  'specialInstructions' : string,
  'quantity' : bigint,
  'menuItemId' : MenuItemId,
}
export interface CartItemInput {
  'customizations' : Array<SelectedCustomization>,
  'specialInstructions' : string,
  'quantity' : bigint,
  'menuItemId' : MenuItemId,
}
export type Cuisine = string;
export interface CustomizationGroup {
  'name' : string,
  'required' : boolean,
  'maxSelections' : bigint,
  'options' : Array<CustomizationOption>,
}
export interface CustomizationOption {
  'name' : string,
  'priceModifierCents' : bigint,
}
export interface DeliveryAddress {
  'id' : AddressId,
  'street' : string,
  'city' : string,
  'zipCode' : string,
  'state' : string,
  'addressLabel' : string,
  'isDefault' : boolean,
}
export interface DeliveryAddressSnapshot {
  'street' : string,
  'city' : string,
  'zipCode' : string,
  'state' : string,
}
export interface MenuItem {
  'id' : MenuItemId,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'customizations' : Array<CustomizationGroup>,
  'restaurantId' : RestaurantId,
  'imageUrl' : string,
  'category' : string,
  'priceCents' : bigint,
}
export type MenuItemId = bigint;
export interface Order {
  'id' : OrderId,
  'subtotalCents' : bigint,
  'status' : OrderStatus,
  'deliveryAddress' : DeliveryAddressSnapshot,
  'deliveryFeeCents' : bigint,
  'createdAt' : Timestamp,
  'totalCents' : bigint,
  'estimatedDeliveryTime' : Timestamp,
  'restaurantId' : RestaurantId,
  'taxCents' : bigint,
  'updatedAt' : Timestamp,
  'restaurantName' : string,
  'customerId' : UserId,
  'items' : Array<CartItem>,
  'stripeSessionId' : string,
}
export type OrderId = bigint;
export type OrderStatus = { 'readyForPickup' : null } |
  { 'cancelled' : null } |
  { 'driverAssigned' : null } |
  { 'inTransit' : null } |
  { 'beingPrepared' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface PlaceOrderInput {
  'restaurantId' : RestaurantId,
  'items' : Array<CartItemInput>,
  'deliveryAddressId' : AddressId,
}
export interface Restaurant {
  'id' : RestaurantId,
  'name' : string,
  'isOpen' : boolean,
  'deliveryTimeMinutes' : bigint,
  'deliveryFeecents' : bigint,
  'imageUrl' : string,
  'cuisine' : Cuisine,
  'rating' : number,
}
export type RestaurantId = bigint;
export interface SelectedCustomization {
  'priceModifierCents' : bigint,
  'selectedOption' : string,
  'groupName' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addDeliveryAddress' : ActorMethod<
    [string, string, string, string, string],
    DeliveryAddress
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'confirmOrderPayment' : ActorMethod<[string], [] | [Order]>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteDeliveryAddress' : ActorMethod<[AddressId], undefined>,
  'deleteMenuItem' : ActorMethod<[MenuItemId], undefined>,
  'deleteRestaurant' : ActorMethod<[RestaurantId], undefined>,
  'filterRestaurants' : ActorMethod<
    [[] | [string], [] | [number], [] | [bigint]],
    Array<Restaurant>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDeliveryAddresses' : ActorMethod<[], Array<DeliveryAddress>>,
  'getMenuItem' : ActorMethod<[MenuItemId], [] | [MenuItem]>,
  'getMenuItems' : ActorMethod<[RestaurantId], Array<MenuItem>>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getOrderHistory' : ActorMethod<[], Array<Order>>,
  'getRestaurant' : ActorMethod<[RestaurantId], [] | [Restaurant]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listRestaurants' : ActorMethod<[], Array<Restaurant>>,
  'placeOrder' : ActorMethod<[PlaceOrderInput, string], Order>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchRestaurants' : ActorMethod<[string], Array<Restaurant>>,
  'setDefaultDeliveryAddress' : ActorMethod<[AddressId], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateDeliveryAddress' : ActorMethod<[DeliveryAddress], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'upsertMenuItem' : ActorMethod<[MenuItem], MenuItem>,
  'upsertRestaurant' : ActorMethod<[Restaurant], Restaurant>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];