/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AddressId = IDL.Nat;
export const DeliveryAddress = IDL.Record({
  'id' : AddressId,
  'street' : IDL.Text,
  'city' : IDL.Text,
  'zipCode' : IDL.Text,
  'state' : IDL.Text,
  'addressLabel' : IDL.Text,
  'isDefault' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'readyForPickup' : IDL.Null,
  'cancelled' : IDL.Null,
  'driverAssigned' : IDL.Null,
  'inTransit' : IDL.Null,
  'beingPrepared' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const DeliveryAddressSnapshot = IDL.Record({
  'street' : IDL.Text,
  'city' : IDL.Text,
  'zipCode' : IDL.Text,
  'state' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const RestaurantId = IDL.Nat;
export const UserId = IDL.Principal;
export const SelectedCustomization = IDL.Record({
  'priceModifierCents' : IDL.Int,
  'selectedOption' : IDL.Text,
  'groupName' : IDL.Text,
});
export const MenuItemId = IDL.Nat;
export const CartItem = IDL.Record({
  'unitPriceCents' : IDL.Nat,
  'menuItemName' : IDL.Text,
  'customizations' : IDL.Vec(SelectedCustomization),
  'specialInstructions' : IDL.Text,
  'quantity' : IDL.Nat,
  'menuItemId' : MenuItemId,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'subtotalCents' : IDL.Nat,
  'status' : OrderStatus,
  'deliveryAddress' : DeliveryAddressSnapshot,
  'deliveryFeeCents' : IDL.Nat,
  'createdAt' : Timestamp,
  'totalCents' : IDL.Nat,
  'estimatedDeliveryTime' : Timestamp,
  'restaurantId' : RestaurantId,
  'taxCents' : IDL.Nat,
  'updatedAt' : Timestamp,
  'restaurantName' : IDL.Text,
  'customerId' : UserId,
  'items' : IDL.Vec(CartItem),
  'stripeSessionId' : IDL.Text,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Cuisine = IDL.Text;
export const Restaurant = IDL.Record({
  'id' : RestaurantId,
  'name' : IDL.Text,
  'isOpen' : IDL.Bool,
  'deliveryTimeMinutes' : IDL.Nat,
  'deliveryFeecents' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'cuisine' : Cuisine,
  'rating' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const CustomizationOption = IDL.Record({
  'name' : IDL.Text,
  'priceModifierCents' : IDL.Int,
});
export const CustomizationGroup = IDL.Record({
  'name' : IDL.Text,
  'required' : IDL.Bool,
  'maxSelections' : IDL.Nat,
  'options' : IDL.Vec(CustomizationOption),
});
export const MenuItem = IDL.Record({
  'id' : MenuItemId,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'customizations' : IDL.Vec(CustomizationGroup),
  'restaurantId' : RestaurantId,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'priceCents' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const CartItemInput = IDL.Record({
  'customizations' : IDL.Vec(SelectedCustomization),
  'specialInstructions' : IDL.Text,
  'quantity' : IDL.Nat,
  'menuItemId' : MenuItemId,
});
export const PlaceOrderInput = IDL.Record({
  'restaurantId' : RestaurantId,
  'items' : IDL.Vec(CartItemInput),
  'deliveryAddressId' : AddressId,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addDeliveryAddress' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [DeliveryAddress],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmOrderPayment' : IDL.Func([IDL.Text], [IDL.Opt(Order)], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteDeliveryAddress' : IDL.Func([AddressId], [], []),
  'deleteMenuItem' : IDL.Func([MenuItemId], [], []),
  'deleteRestaurant' : IDL.Func([RestaurantId], [], []),
  'filterRestaurants' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Float64), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Restaurant)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDeliveryAddresses' : IDL.Func([], [IDL.Vec(DeliveryAddress)], ['query']),
  'getMenuItem' : IDL.Func([MenuItemId], [IDL.Opt(MenuItem)], ['query']),
  'getMenuItems' : IDL.Func([RestaurantId], [IDL.Vec(MenuItem)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getRestaurant' : IDL.Func([RestaurantId], [IDL.Opt(Restaurant)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  'placeOrder' : IDL.Func([PlaceOrderInput, IDL.Text], [Order], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchRestaurants' : IDL.Func([IDL.Text], [IDL.Vec(Restaurant)], ['query']),
  'setDefaultDeliveryAddress' : IDL.Func([AddressId], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateDeliveryAddress' : IDL.Func([DeliveryAddress], [], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'upsertMenuItem' : IDL.Func([MenuItem], [MenuItem], []),
  'upsertRestaurant' : IDL.Func([Restaurant], [Restaurant], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AddressId = IDL.Nat;
  const DeliveryAddress = IDL.Record({
    'id' : AddressId,
    'street' : IDL.Text,
    'city' : IDL.Text,
    'zipCode' : IDL.Text,
    'state' : IDL.Text,
    'addressLabel' : IDL.Text,
    'isDefault' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'readyForPickup' : IDL.Null,
    'cancelled' : IDL.Null,
    'driverAssigned' : IDL.Null,
    'inTransit' : IDL.Null,
    'beingPrepared' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const DeliveryAddressSnapshot = IDL.Record({
    'street' : IDL.Text,
    'city' : IDL.Text,
    'zipCode' : IDL.Text,
    'state' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const RestaurantId = IDL.Nat;
  const UserId = IDL.Principal;
  const SelectedCustomization = IDL.Record({
    'priceModifierCents' : IDL.Int,
    'selectedOption' : IDL.Text,
    'groupName' : IDL.Text,
  });
  const MenuItemId = IDL.Nat;
  const CartItem = IDL.Record({
    'unitPriceCents' : IDL.Nat,
    'menuItemName' : IDL.Text,
    'customizations' : IDL.Vec(SelectedCustomization),
    'specialInstructions' : IDL.Text,
    'quantity' : IDL.Nat,
    'menuItemId' : MenuItemId,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'subtotalCents' : IDL.Nat,
    'status' : OrderStatus,
    'deliveryAddress' : DeliveryAddressSnapshot,
    'deliveryFeeCents' : IDL.Nat,
    'createdAt' : Timestamp,
    'totalCents' : IDL.Nat,
    'estimatedDeliveryTime' : Timestamp,
    'restaurantId' : RestaurantId,
    'taxCents' : IDL.Nat,
    'updatedAt' : Timestamp,
    'restaurantName' : IDL.Text,
    'customerId' : UserId,
    'items' : IDL.Vec(CartItem),
    'stripeSessionId' : IDL.Text,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Cuisine = IDL.Text;
  const Restaurant = IDL.Record({
    'id' : RestaurantId,
    'name' : IDL.Text,
    'isOpen' : IDL.Bool,
    'deliveryTimeMinutes' : IDL.Nat,
    'deliveryFeecents' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'cuisine' : Cuisine,
    'rating' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CustomizationOption = IDL.Record({
    'name' : IDL.Text,
    'priceModifierCents' : IDL.Int,
  });
  const CustomizationGroup = IDL.Record({
    'name' : IDL.Text,
    'required' : IDL.Bool,
    'maxSelections' : IDL.Nat,
    'options' : IDL.Vec(CustomizationOption),
  });
  const MenuItem = IDL.Record({
    'id' : MenuItemId,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'customizations' : IDL.Vec(CustomizationGroup),
    'restaurantId' : RestaurantId,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'priceCents' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const CartItemInput = IDL.Record({
    'customizations' : IDL.Vec(SelectedCustomization),
    'specialInstructions' : IDL.Text,
    'quantity' : IDL.Nat,
    'menuItemId' : MenuItemId,
  });
  const PlaceOrderInput = IDL.Record({
    'restaurantId' : RestaurantId,
    'items' : IDL.Vec(CartItemInput),
    'deliveryAddressId' : AddressId,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addDeliveryAddress' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [DeliveryAddress],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmOrderPayment' : IDL.Func([IDL.Text], [IDL.Opt(Order)], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteDeliveryAddress' : IDL.Func([AddressId], [], []),
    'deleteMenuItem' : IDL.Func([MenuItemId], [], []),
    'deleteRestaurant' : IDL.Func([RestaurantId], [], []),
    'filterRestaurants' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Float64), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Restaurant)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDeliveryAddresses' : IDL.Func(
        [],
        [IDL.Vec(DeliveryAddress)],
        ['query'],
      ),
    'getMenuItem' : IDL.Func([MenuItemId], [IDL.Opt(MenuItem)], ['query']),
    'getMenuItems' : IDL.Func([RestaurantId], [IDL.Vec(MenuItem)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getRestaurant' : IDL.Func(
        [RestaurantId],
        [IDL.Opt(Restaurant)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
    'placeOrder' : IDL.Func([PlaceOrderInput, IDL.Text], [Order], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchRestaurants' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Restaurant)],
        ['query'],
      ),
    'setDefaultDeliveryAddress' : IDL.Func([AddressId], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateDeliveryAddress' : IDL.Func([DeliveryAddress], [], []),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'upsertMenuItem' : IDL.Func([MenuItem], [MenuItem], []),
    'upsertRestaurant' : IDL.Func([Restaurant], [Restaurant], []),
  });
};

export const init = ({ IDL }) => { return []; };